### ISSUE TITLE
thread 'main' panicked at src/parse.rs:111:46: -l specified file could not be opened properly. Make sure this file exists. Exiting.: Os { code: 2, kind: NotFound, message: "No such file or directory" }

### ISSUE THREAD

**Issue by jolespin** [bluenote-1577/skani#28]
I'm not sure what's going on but I made sure that my file exists.  

**Any idea what's throwing this error?** 

Here's my `skani` version: 

```
$ skani --version
skani 0.2.1
```
Here's my genome file paths file:
```
(VEBA-cluster_env) jovyan@jupyter-jolespin:~/Clustering/Genomes/Prokaryotic$ GENOMES="genomes.filepaths.contamination_lt10.list"
(VEBA-cluster_env) jovyan@jupyter-jolespin:~/Clustering/Genomes/Prokaryotic$ wc -l ${GENOMES}
58235 genomes.filepaths.contamination_lt10.list
```

Here's my `skani command`:

```
(VEBA-cluster_env) jovyan@jupyter-jolespin:~/Clustering/Genomes/Prokaryotic$ export RUST_BACKTRACE=full
(VEBA-cluster_env) jovyan@jupyter-jolespin:~/Clustering/Genomes/Prokaryotic$ skani triangle --sparse -t 16 -l {GENOMES} -o skani_output/skani_output.contamination_lt10.tsv --ci --min-af 15.0 -s 80.0 -c 125 -m 1000 --medium
```

Here's my error:

```
thread 'main' panicked at src/parse.rs:111:46:
-l specified file could not be opened properly. Make sure this file exists. Exiting.: Os { code: 2, kind: NotFound, message: "No such file or directory" }
stack backtrace:
   0:     0x55e0e8344540 - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55e0e8344540 - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55e0e8344540 - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55e0e8344540 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x55e0e826ca5c - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x55e0e826ca5c - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x55e0e831372d - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x55e0e8345aee - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x55e0e8345aee - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x55e0e83456d3 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x55e0e83466e8 - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0x55e0e83466e8 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:     0x55e0e83461c2 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
  13:     0x55e0e8346126 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x55e0e8346111 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:     0x55e0e821b702 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0x55e0e821bb39 - core::result::unwrap_failed::hccb456d39e9c31fc
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
  17:     0x55e0e82eb615 - skani::parse::parse_params::hee7ed757d493d092
  18:     0x55e0e830bf96 - skani::main::hf0a8a944fff623ac
  19:     0x55e0e822a9c3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1d1e56655e7e787d
  20:     0x55e0e82f5d93 - main
  21:     0x7f77ba770d90 - <unknown>
  22:     0x7f77ba770e40 - __libc_start_main
  23:     0x55e0e822a905 - <unknown>
Aborted (core dumped)
```

**Comment by bluenote-1577** [comment]
Hi @jolespin,

Hmm... your guess is as good as mine here. The code that throws this error just uses Rust's internal library to open a file and throws this error if it can't. I'm not doing any additional processing. 

So for some reason the library can't open your file. I looked at the docs and here is what it says:

---------------------------------------------------------------
[Errors](https://doc.rust-lang.org/std/fs/struct.OpenOptions.html#errors)
This function will return an error under a number of different circumstances. Some of these error conditions are listed here, together with their [io::ErrorKind](https://doc.rust-lang.org/std/io/enum.ErrorKind.html). The mapping to [io::ErrorKind](https://doc.rust-lang.org/std/io/enum.ErrorKind.html)s is not part of the compatibility contract of the function.

[NotFound](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.NotFound): The specified file does not exist and neither create or create_new is set.
[NotFound](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.NotFound): One of the directory components of the file path does not exist.
[PermissionDenied](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.PermissionDenied): The user lacks permission to get the specified access rights for the file.
[PermissionDenied](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.PermissionDenied): The user lacks permission to open one of the directory components of the specified path.
[AlreadyExists](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.AlreadyExists): create_new was specified and the file already exists.
[InvalidInput](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.InvalidInput): Invalid combinations of open options (truncate without write access, no access mode set, etc.).
The following errors don’t match any existing [io::ErrorKind](https://doc.rust-lang.org/std/io/enum.ErrorKind.html) at the moment:

One of the directory components of the specified file path was not, in fact, a directory.
Filesystem-level errors: full disk, write permission requested on a read-only file system, exceeded disk quota, too many open files, too long filename, too many symbolic links in the specified path (Unix-like systems only), etc.

-------------------------------------------


Idea: there's no $ sign on your command... is this an issue?

**Comment by jolespin** [comment]
I forgot the $ character on the variable lol. my bad
